Use builtin map to list function.
exercism/erlang pull request #497
Opened 2021-12-19 17:27 UTC by fmv1992

The tests currently rely on a function not sketched in `dict:to_list`.

So we should either:

*   Add that function to parallel_letter_frequency_tests.erl .

*   Use the builtin `maps:to_list` function on the existing tests (I chose this route).

2022-01-03 16:04 UTC, fmv1992 commented
@NobbZ , should I tag someone here? (first time contribution)

2022-01-03 16:10 UTC, NobbZ commented
Thank you for bringing this issue back to my attention.

I do not remember exactly why we have used `dict` here.

Though I don't want to approve or merge without a closer look for the reasons.

Please be a bit patient, I'll schedule another look for the upcoming weekend, hoping that new year's things have settled then.

2022-01-17 17:55 UTC, NobbZ requested changes
Okay, found some time to take a closer look. The exercise has been added in 2015, when the main target was OTP 17. It already had the maps feature in theory, but using them was mostly considered an antipattern back then if I recall consider, as their implementation was slow.

Also on OTP 16 which was still broadly used back then IIRC, maps didn't even exist.

So I think it is just some debt from that time and we can happily agree on `maps` being the better way to do the exercise.

Though, as we are using proper maps now, we can assert on map-equality and do not need to use the intermediate list anymore which probably has been used to make errors a little bit nicer.

Would you mind changing the assertions accordingly?

We also do not need the list conversion anymore then.

2022-01-19 21:32 UTC, fmv1992 commented
@NobbZ  , let me know what you think about these changes.

2022-01-19 22:44 UTC, NobbZ approved these changes
This looks good to me, though I can't check the CI run currently. I can not find it in the app.

I'll check again tomorrowish and merge if it passed.

2022-01-19 22:48 UTC, NobbZ commented
Oh... My bad... You need to fix the example implementation as well

2022-01-19 22:49 UTC, NobbZ requested changes
Please fix example

2022-01-29 22:46 UTC, fmv1992 commented
@NobbZ , friendly reminder here.

2022-01-30 15:31 UTC, NobbZ approved these changes

2022-01-30 15:31 UTC, merged