Add eliuds-eggs
exercism/erlang pull request #576
Opened 2024-04-13 00:49 UTC by BNAndras

For #48in24. Forum thread at https://forum.exercism.org/t/add-additional-exercises-exercises/10727/3

2024-04-13 01:01 UTC, BNAndras commented
The files worked locally on 26. I’ll troubleshoot it this weekend.

2024-04-13 07:58 UTC, NobbZ commented
I sadly won't have the time to help any debugging before tomorrow, but be assured, I never have seen that error before.

2024-04-28 04:28 UTC, BNAndras commented
CI passes and I've got a better grasp on the tooling. :)

2024-04-28 08:13 UTC, NobbZ requested changes

2024-04-28 08:13 UTC, NobbZ commented on exercises/practice/eliuds-eggs/.meta/example.erl
> +    eggCount(Number bsr 1, Acc + (Number band 1)).
```suggestion
-export([egg_count/1]).


egg_count(Number) -> egg_count(Number, 0).

egg_count(0, Acc) -> Acc;
egg_count(Number, Acc) when Number > 0 ->
    egg_count(Number bsr 1, Acc + (Number band 1)).
```

Please stay consistent with the naming conventions in the repo. Unless I missed some exercises, snake case is preferred for function names.

2024-05-02 16:24 UTC, NobbZ approved these changes

2024-05-02 16:25 UTC, merged